
$terrains = {
  "blank" =>          ["@d ",   " ",       "@d "],
	"inside" =>         ["@d[",    " ",      "@d]"],
	"city" =>           ["@d.",    " ",      "@d."],
	"field" =>          ["@g,@d",  " ",      "@g`@d"],
	"hills" =>          ["@G;@d",  " ",      "@G;@d"],
	"mountain" =>       ["@y/@d",  " ",      "@y\@d"],
	"water" =>          ["@B~@d",  " ",      "@B~@d"],
	"air" =>            ["@c.@d",  " ",      "@c.@d"],
	"desert" =>         ["@y~@d",  " ",      "@y~@d"],
	"quicksand" =>      ["@Y%@d",  " ",      "@Y%@d"],
	"underwater" =>     ["@b~@d",  " ",      "@b~@d"],
	"ice" =>            ["@C~@d",  " ",      "@C~@d"],
	"underground" =>    ["@B.@d",  " ",      "@B.@d"],
	"eastwestroad" =>   ["@d-",    " ",      "@d-"],
	"northsouthroad" => ["@d.",    " ",      "@d."],
	"river" =>          ["@C~@d",  " ",      "@C~@d"],
	"volcano" =>        ["@R/@d",  " ",      "@R\@d"],
	"cave" =>           ["@b%@d",  " ",      "@b%@d"],
	"dungeon" =>        ["@W\#@d", " ",      "@W\#@d"],
	"castle" =>         ["@W\#@d", "@W\#@d", "@W\#@d"],
	"forest" =>         ["@g(@d",  " ",      "@g*@d"],
	"townsquare"   =>   ["@R(@d",  "@W~@d",  "@R)@d"],
	"market"   =>       ["@Y$@d",  "@W~@d",  "@Y$@d"],
	"temple" =>         ["@c{@d",  "@W+@d",  "@c}@d"],
  "plains" =>         ["@g.@d",  "@y,@d",  "@G.@d"],
}